### PR TITLE
Laravel 10 Compatibility

### PR DESCRIPTION
**Pull request by richdynamix**
This PR adds compatibility with Laravel 10. Dependencies are updated along with the GitHub actions run-tests workflow.

Dropped support for Laravel 8 and PHP 8.0

### CODE REVIEW

**Comment by stephenjude** [comment]
@richdynamix thanks for this PR. 

Can you check why the test workflow is failing?

**Comment by richdynamix** [comment]
Hi @stephenjude 

I am investigating now. It seems to be failing to find `filament-support::grid` within the core. I have ran the test on the base branch and same issue.

I'll let you know when I have found a solution.

**Comment by stephenjude** [comment]
Well done @richdynamix 

looks like we are dealing with issues from FilamentPHP itself. I will be waiting for your feedback.

**Comment by ShaungBhone** [comment]
@richdynamix @stephenjude. I'm waiting this PR for my next project.

**Pull request merged**
